name: Run E2E Tests
on: [pull_request]
jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      api-solid-pg:
        image: bitnami/postgresql:latest
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: apisolid

    steps:
      - uses: actions/checkout@v4
      - name: Install NodeJS # Sometimes we don't need this step if the runner already has it installed
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm' # use pnpm cache
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install dependencies with pnpm
        run: pnpm install --frozen-lockfile # installing dependencies from pnpm-lock.yaml
      - name: Generate Prisma client
        run: pnpm prisma generate
      - name: Run tests
        run: pnpm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"